<img src="https://raw.githubusercontent.com/toqafotoh/TeamPreparation/main/Blue%20and%20Yellow%20Playful%20Doodle%20Digital%20Brainstorm%20Presentation.png">

<span style="color: #8f3b43; font-size: 35px;">Useless Note 🙈 </span>
### 💥 The name "NumPy" is short for "Numerical Python." oohh

In [3]:
#imorting the library to work with
import numpy as np

In [9]:
#the simplist and first way to create numpy array
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)
#as we see the type isn't list, and even when printing it , it's preceded by the word array

numpy.ndarray

In [13]:
#you can create it with passing alist, tuple,set to this fuction
arr = np.array((1, 2, 3, 4, 5))
arr

array([1, 2, 3, 4, 5])

In [13]:
'''
or create it with the function "arange"
it can take a number and make you an array from 1 to it 
or take a start point , ending point and step .. as range function
'''
arr1 = np.arange(1000000)
arr2 = np.arange(1,50,2)
print(arr1)
print(arr2)

arr3 = np.arange(1,13).reshape(3,4) 
print(arr3)
#this line of code let you reshape the array 
#But 💥 the multiplication of x and y must = n elements, or it will cause an error
#here we have from 1-->12 so 12 element and 3*4=12

[     0      1      2 ... 999997 999998 999999]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
np.random.seed(42)
# this line of code for the random functions to give you the same output no matter how many times u run the code

In [11]:
arr1 = np.random.rand(3,3)
arr2 = np.random.random((6))
'''
random.rand and random.random is 2 functions which return an array
consist of float numbers from 0 to 1 , and the 1 is exclusive
but the different is the paramters ,
so .rand you can specify its dimensions but .random is only 1D 
'''
arr3 = np.random.randint(1,10,size=(2,4))
# .randint returns integer numbers not float
print(f"random.rand :\n {arr1}\n")
print(f"random.random :\n {arr2}\n")
print(f"random.randint :\n {arr3}\n")

random.rand :
 [[0.58029804 0.83031445 0.81534501]
 [0.49944706 0.79939526 0.97445396]
 [0.30999673 0.6296296  0.96771591]]

random.random :
 [0.27809304 0.26776166 0.50810576 0.91281503 0.10278619 0.66605493]

random.randint :
 [[7 3 4 8]
 [3 6 5 7]]



In [30]:
arr = np.linspace(0, 1, 11, endpoint=True)
arr
#linspace is different that the third argument is the number of elements 


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

endpoint here is an argument that determine whether the ending value in included or not <br/>
<span style="color: #8f3b43; font-size: 35px;">✨NOTE :</span><br/>
<span style="color: blue; font-size: 20px;">you can check the documentation of any function to see its arguments and their importance by typing "function name"+"?"</span>

In [31]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is Fals

<span style="color: #8f3b43; font-size: 25px;">Special types of arrays</span>

In [23]:
# zeros and ones functions create a 1 dimensional array of n elements
zeros_array = np.zeros(5) #olny zeros array
ones_array = np.ones(3) #only ones array
# eye is a function that makes 2D identity matrix of n*n 
identity_matrix = np.eye(3) 
empty_array = np.empty((2,3))
#empty function returns garbage float values
print(f"zeros_array :\n{zeros_array}\n")
print(f"ones_array :\n{ones_array}\n")
print(f"identity_matrix :\n{identity_matrix}\n")
print(f"empty_array :\n{empty_array}\n")

zeros_array :
[0. 0. 0. 0. 0.]

ones_array :
[1. 1. 1.]

identity_matrix :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

empty_array :
[[4.24399158e-314 8.48798317e-314 1.27319747e-313]
 [1.69759663e-313 2.12199579e-313 2.54639495e-313]]



In [24]:
# and btw you can specify any datatype you want for the matrix
empty_array_int = np.empty((2, 3), dtype=int)  
empty_array_bool = np.empty((2, 3), dtype=bool) 
#True corresponds to any non-zero value , and False corresponds to 0 value
print(f"empty_array_int :\n{empty_array_int}\n")
print(f"empty_array_bool :\n{empty_array_bool}\n")

empty_array_int :
[[         0 1072693248          0]
 [1072693248          0 1072693248]]

empty_array_bool :
[[ True  True  True]
 [ True  True  True]]



In [31]:
'''
you can make an array contains T and F based on specific conidtion
create your normal array and evaluate the condtion like the following
'''
arr = np.array([1, 3, 5, 2, 6, 8])
bool_array = (arr >= 2) & (arr <= 6)
print(bool_array)

[False  True  True  True  True False]


#### ✨ NOTE : 

In [19]:
# you can also use the function "zeros_like" , to give you the same dimensions
arr = np.array([
    [6, 5],
    [2, 3],
    [1, 4]
])
zeros_arr = np.zeros_like(arr)
ones_arr = np.ones_like(arr)
print(zeros_arr)
print(ones_arr)

[[0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]]


In [48]:
'''
np.tile is a function that allow you to repeat an array along axes
'''
arr = np.array([[1, 2],
                [3, 4]])

tiled_array = np.tile(arr,(2,2))
# ✨try to change this (2,2) to (3) or any other numbers to see the difference
print(f"array: \n{arr}\n")
print(f"tiled_array: \n{tiled_array}\n")


array: 
[[1 2]
 [3 4]]

tiled_array: 
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]



In [24]:
def condition(x,y):
    return x+y
toto = np.fromfunction(condition, (3, 3))
toto

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [1]:
'''
the previous function is creating an array of 3 cols & 3 rows 
and it has the numbers from 0 to 2 for x and y
as x  = 3 numbers and y = 3 numbers 
x = [0,1,2]
y= [0,1,2]
it makes all the combinations between them and pass that to the function that you wrote
'''

'''
Iterations
When x=0 and y=0, the function condition(0, 0) is called.
When x=0 and y=1, the function condition(0, 1) is called.
When x=0 and y=2, the function condition(0, 2) is called.
When x=1 and y=0, the function condition(1, 0) is called.
When x=1 and y=1, the function condition(1, 1) is called.
When x=1 and y=2, the function condition(1, 2) is called.
When x=2 and y=0, the function condition(2, 0) is called.
When x=2 and y=1, the function condition(2, 1) is called.
When x=2 and y=2, the function condition(2, 2) is called.
'''

'\nIterations\nWhen x=0 and y=0, the function condition(0, 0) is called.\nWhen x=0 and y=1, the function condition(0, 1) is called.\nWhen x=0 and y=2, the function condition(0, 2) is called.\nWhen x=1 and y=0, the function condition(1, 0) is called.\nWhen x=1 and y=1, the function condition(1, 1) is called.\nWhen x=1 and y=2, the function condition(1, 2) is called.\nWhen x=2 and y=0, the function condition(2, 0) is called.\nWhen x=2 and y=1, the function condition(2, 1) is called.\nWhen x=2 and y=2, the function condition(2, 2) is called.\n'

<span style="color: #8f3b43; font-size: 35px;">Matrices Operations 💫</span>

In [32]:
# each matrix have a rank and shape 
# the rank is the number of dimensions , and the shape is n rows ,n columns
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)  #prints the rank
print(arr.shape) #prints the shape

2
(2, 3)


In [37]:
matrix = np.array([[1, 2],
                  [3, 4]])

# this line of code computes the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)
# to calculate the transpose you can use .T or the following function
transpose_matrix = matrix.T
transpose2_matrix = np.transpose(matrix)

# you can also claculate the deteminant of a matrix 
determinant = np.linalg.det(matrix)
'''
np.linalg.eig is a function that returns the eigenvalues & vectors 
it's a topic in linear algebra that we will need later in ML
'''
eigenvalues, eigenvectors = np.linalg.eig(matrix)
'''
and this is a function that let you fill the diagonal with the value that you want
it changes the original matrix not assign it to another var
'''
np.fill_diagonal(matrix,1)
print(f"inverse_matrix : \n{inverse_matrix}\n")
print(f"transpose_matrix : \n{transpose_matrix}\n")
print(f"transpose2_matrix : \n{transpose2_matrix}\n")
print(f"determinant : \n{determinant}\n")
print(f"eigenvalues : \n{eigenvalues}\n")
print(f"eigenvectors : \n{eigenvectors}\n")
print(f"ones_diagonal : \n{matrix}\n")

inverse_matrix : 
[[-2.   1. ]
 [ 1.5 -0.5]]

transpose_matrix : 
[[1 3]
 [2 1]]

transpose2_matrix : 
[[1 3]
 [2 1]]

determinant : 
-2.0000000000000004

eigenvalues : 
[-0.37228132  5.37228132]

eigenvectors : 
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

ones_diagonal : 
[[1 2]
 [3 1]]



In [40]:
# you can join 2 array amoung rows axis=0, or columns axis=1
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6], 
                 [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(f"row concatenation :\n {arr}\n")
arr = np.concatenate((arr1, arr2), axis=1)
print(f"column concatenation :\n {arr}\n")

row concatenation :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

column concatenation :
 [[1 2 5 6]
 [3 4 7 8]]



In [43]:
# as we concatenated 2 arrays let's try to split them
# using "array_split" function

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sub_arrays = np.array_split(arr, 3)
#the second parameter is the number of equal sizes arrays
print (f"sub_arrays : {sub_arrays}\n")
for i, sub_array in enumerate(sub_arrays):
    print(f"Sub-array{i+1}: {sub_array}")

'''
enumerate is a function that allows you to loop over an iterable 
(like a list, tuple, or string)
and keep track of the index of the current item
as it returns the index and the element
'''

sub_arrays : [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

Sub-array1: [1 2 3]
Sub-array2: [4 5 6]
Sub-array3: [7 8 9]


In [57]:
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

#normal addtion must done on 2 arrays of the same dimension
print (f"arr1 + arr2 :\n {arr1 + arr2}")
print (f"arr1 + 5 :\n {arr1 + 5}")
print (f"arr1 - arr1 :\n {arr1 - arr1}")


arr1 + arr2 :
 [[ 6  8]
 [10 12]]
arr1 + 5 :
 [[6 7]
 [8 9]]
arr1 - arr1 :
 [[0 0]
 [0 0]]


<span style="color: #8f3b43; font-size: 35px; font-weight: bold;">🔶 Multiplication</span>

<span style="color: #8f3b43; font-size: 20px;">There are three different multiplication concepts, so let's take a look:</span><br/>
<br/>
<span style="color: #4CAF50; font-size: 27px; font-weight: bold;">🔸 1st: Element-wise Multiplication (*)</span><br/>
<span style="color: black; font-size: 23px;">This type multiplies each element with the corresponding one, and it requires the two arrays to be the same shape.</span><br/>
<br/>
<span style="color: #4CAF50; font-size: 27px; font-weight: bold;">🔸 2nd: Matrix Multiplication or Dot Product (np.dot(), .dot(), and @)</span><br/>
<span style="color: black; font-size: 23px;">This type requires the number of columns in the first matrix to be equal to the number of rows in the second matrix.</span><br/>
<br/>
<span style="color: #4CAF50; font-size: 27px; font-weight: bold;">🔸 3rd: Matrix-Vector Multiplication (using the same functions but with a vector)</span><br/>
<span style="color: black; font-size: 23px;">This type multiplies each row of the matrix by the corresponding element of the vector.</span><br/>
<br/>


In [60]:
vector = np.array([9, 10])